### ISSUE TITLE
Version 5.1.1 of platformio-node-helpers breaks the VS Code extension

### ISSUE THREAD

**Issue by skleeschulte** [platformio/platformio-node-helpers#10]
On my system, a version 5.1.1 of platformio-node-helpers gets installed when doing a fresh install of the PlatformIO IDE extension in VS Code. It looks like [recent changes to src/misc.js](https://github.com/platformio/platformio-node-helpers/commit/d68f6a7abfcdc9b44d7a82e1ab22a55546b6ee9a#diff-09b4071ac2580135011b3b0c784ee17d) are breaking functionality of the PlatformIO IDE VS code extension, see the following issues:

- https://github.com/platformio/platformio-vscode-ide/issues/1209
- https://github.com/platformio/platformio-vscode-ide/issues/1210
- https://github.com/platformio/platformio-vscode-ide/issues/1211

**Comment by ivankravets** [comment]
Sorry for the issue. Please update to v1.9.2 https://github.com/platformio/platformio-vscode-ide/releases/tag/v1.9.2

![Screen Shot 2019-10-20 at 10 31 28](https://user-images.githubusercontent.com/1760209/67156265-d0dc9500-f324-11e9-8808-16a25715997d.png)
