### ISSUE TITLE
Project tasks discovery broken with platformio.ini `extends` option

### ISSUE THREAD

**Issue by cailloumajor** [platformio/platformio-node-helpers#12]
Hello,

Given this example `platformio.ini`:

 ```ini
[platformio]
default_envs = release

[d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

[with_exceptions]
build_unflags = -fno-exceptions
build_flags = -fexceptions

[env:release]
extends = d1_mini

[env:debug]
extends = d1_mini, with_exceptions
build_type = debug
```

PlatformIO extension for VSCode does not discover the environments and thus does not add corresponding project tasks.
This is because this library only looks for the `platform` option in each `[env:NAME]` section:
https://github.com/platformio/platformio-node-helpers/blob/7f59b25023c2b7e5b4c190b0ad61f81ef7017775/src/project/tasks.js#L143-L147

**Comment by cailloumajor** [comment]
I am working on a fix and will submit a pull request soon.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-node-helpers/commit/10f0b9406909d009a1ce337175593cf26a830e1c
