### ISSUE TITLE
Custom platform specific tasks

### ISSUE THREAD

**Issue by ajaybhargav** [platformio/platformio-node-helpers#17]
Based on the discussion I had on [platformio community](https://community.platformio.org/t/platform-specific-project-task/13966):

I figured that there is no direct way for platform source to add new task for user project, so that user do not have to create its own task.json to do platform specific tasks.
e.g. For the custom platform I am developing (https://github.com/siwiembedded/platform-siwigsm)
I need to add task for user to reflash GSM module core. I can do that from command line but it would have been great if I could add a project task which says "Re-flash Core".

**Comment by ivankravets** [comment]
Implemented in PIO Core 4.4, PIO IDE 2.0. See example of dev-platform:
- https://github.com/platformio/platform-atmelavr/blob/develop/builder/main.py#L171

You need PIO IDE 2.0 for VSCode https://community.platformio.org/t/platformio-ide-for-vscode-2-0-beta-help-us-with-testing/14097

**Comment by ajaybhargav** [comment]
when is the PIO IDE 2.0 release planned?

**Comment by ivankravets** [comment]
I think at the end of this month. It depends on PIO Core 4.4 release https://github.com/platformio/platformio-core/blob/develop/HISTORY.rst
