### ISSUE TITLE
SSL verification during installation on corporate networks

### ISSUE THREAD

**Issue by notiflux** [platformio/platformio-node-helpers#21]
When installing the PlatformIO VSCode extension on a network that uses custom root certificate authorities (like on many corporate networks), the SSL verification fails.

I used to be able to bypass this by disabling SSL verification in VSCode, but apart from being an ugly workaround, it also does not work anymore (I get an error saying SSL verification should be turned on).

The only way I found to install the extension now is to decode [the base64 encoded zip-file](https://github.com/platformio/platformio-node-helpers/blob/master/src/installer/get-platformio.js#L41), extract it, append the custom root CA to `certifi/cacert.pem`, re-compress it, base64-encode it, and replace it in this module's index.js.

The underlying issue obviously isn't PlatformIO here but rather the fact that pip/urllib is using [certifi](https://github.com/certifi/python-certifi) which by design only checks against [Mozilla's included certificates list](https://wiki.mozilla.org/CA/Included_Certificates).

My workaround is not intended by certifi, the CA store is supposed to be static and adding custom certificates is not supported.
I'm not sure what a good way to approach this would be, but I'm sure someone here will have better ideas than me.

**Comment by ivankravets** [comment]
Could you try this workaround https://requests.readthedocs.io/en/latest/user/advanced/#proxies? 

Setting `REQUESTS_CA_BUNDLE` environment variable.

**Comment by ivankravets** [comment]
Please reopen if you still need help
