### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by medentem** [platformio/platformio-node-helpers#22]
Hello - I am attempting to use this repo to ensure PIO is installed when my electron app starts up. Is there a guide on how to properly use this package to install PIO? I am having a lot of trouble getting the install to work by reverse engineering the install process.

Attempting to include into this app: https://github.com/medentem/electron-flasher/

Thanks in advance.

**Comment by ivankravets** [comment]
This repo is used in https://github.com/platformio/platformio-vscode-ide

- https://github.com/platformio/platformio-vscode-ide/blob/develop/src/installer/manager.js

**Comment by medentem** [comment]
Awesome. Thank you. I'll take a look.
