### ISSUE TITLE
URL encoding elements in vscode extension reports

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-node-helpers#7]
As far as I can tell, this is responsible for basically mangling the automated github issue templates as it appears the string is being double URI encoded, since it seem querystringify does URL safe encoding itself.  If [qs can be used instead](https://github.com/ljharb/qs#stringifying), you can instruct it to not encode URL strings, or if querystringify is doing the job properly, drop the encodeURIComponent calls? qs would need to be tested properly as a quick cmd line test suggests it will work, but I was only testing encoding, it didn't have data to process.

i.e. with qs instead of querystringify the line would instead look like 
```
return `https://github.com/platformio/platformio-vscode-ide/issues/new?${qs.stringify(
    { title: encodeURIComponent(title), body: encodeURIComponent(description) }, { encode: false })}`;
```
or if querystringify is indeed doing url safe encoding properly 

```
return `https://github.com/platformio/platformio-${process.env.PLATFORMIO_CALLER || 'vscode'}-ide/issues/new?${qs.stringify(
    { title: title, body: description })}`;
```
https://github.com/platformio/platformio-node-helpers/blob/b3a24e19e47ccc198a1bd1f4f9629b414c95fd28/src/misc.js#L208-L209

**Comment by ivankravets** [comment]
Thanks! Fixed.

**Comment by ivankravets** [comment]
Please re-test with https://github.com/platformio/platformio-vscode-ide/releases/tag/v1.8.0-beta.1
