### ISSUE TITLE
Suggestion: Automatically labeling error report issues

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-node-helpers#8]
I just came across [a reference that issue queries could also automate labeling](https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters)... so it would be great if you could add either a single, or a couple of labels with say a prefix of `auto` which would allow easy separation of auto-generated issues, and manually created issues... and if you do more than the one auto message, well, now you have categories! :) 

so relevant bit of the URL could look like ... `-ide/issues/new?labels=auto&${qs.stringify` ...

for just a `auto` label (note: it looks like the the label needs exist before it works)

https://github.com/platformio/platformio-node-helpers/blob/5dbe01b23f9212758ba209f69cf0534bf36fd19a/src/misc.js#L204

**Comment by ivankravets** [comment]
Thanks! Resolved in https://github.com/platformio/platformio-node-helpers/releases/tag/v5.0.3

**Comment by pfeerick** [comment]
I noticed that there is at least one new report on the vscode issue tracker from v1.8.2... and it didn't auto-tag... and just realised there was this caveat (hence why it worked when I was testing it on my own scratch repo): 

> You must have the proper permissions for any action to use the equivalent query parameter. For example, you must have permission to add a label to an issue to use the labels query parameter.
